export default {
    INITIALIZE: {
        REQUEST: 'MATCH_INITIALIZE_REQUEST',
        SUCCESS: 'MATCH_INITIALIZE_SUCCESS',
        FAILURE: 'MATCH_INITIALIZE_FAILURE'
    },
    ACTIVATE_FORMATION: 'MATCH_ACTIVATE_FORMATION',
    SET_FORMATION: 'MATCH_SET_FORMATION',
    RECORD: 'MATCH_RECORD',
    RECORD_DELETE: 'MATCH_RECORD_DELETE',
    CREATE: {
        REQUEST: 'MATCH_CREATE_REQUEST',
        SUCCESS: 'MATCH_CREATE_SUCCESS',
        FAILURE: 'MATCH_CREATE_FAILURE'
    }
}