export default {
    REGISTER: {
        REQUEST: 'MEMBER_REGISTER_REQUEST',
        SUCCESS: 'MEMBER_REGISTER_SUCCESS',
        FAILURE: 'MEMBER_REGISTER_FAILURE'
    },
    LOGIN: {
        REQUEST: 'MEMBER_LOGIN_REQUEST',
        SUCCESS: 'MEMBER_LOGIN_SUCCESS',
        FAILURE: 'MEMBER_LOGIN_FAILURE'
    },
    LOGOUT: 'MEMBER_LOGOUT'
}