export default {
    REGISTER: {
        REQUEST: 'PLAYER_REGISTER_REQUEST',
        SUCCESS: 'PLAYER_REGISTER_SUCCESS',
        FAILURE: 'PLAYER_REGISTER_FAILURE'
    },
    LOGIN: {
        REQUEST: 'PLAYER_LOGIN_REQUEST',
        SUCCESS: 'PLAYER_LOGIN_SUCCESS',
        FAILURE: 'PLAYER_LOGIN_FAILURE'
    },
    LOGOUT: 'PLAYER_LOGOUT'
}