export default {
    REGISTER: {
        REQUEST: 'PLAYER_REGISTER_REQUEST',
        SUCCESS: 'PLAYER_REGISTER_SUCCESS',
        FAILURE: 'PLAYER_REGISTER_FAILURE'
    },
    FIND_BY_TEAM: {
        REQUEST: 'PLAYER_FIND_BY_TEAM_REQUEST',
        SUCCESS: 'PLAYER_FIND_BY_TEAM_SUCCESS',
        FAILURE: 'PLAYER_FIND_BY_TEAM_FAILURE'
    }
}