export default {
    REGISTER: {
        REQUEST: 'TEAM_REGISTER_REQUEST',
        SUCCESS: 'TEAM_REGISTER_SUCCESS',
        FAILURE: 'TEAM_REGISTER_FAILURE'
    },
    LOGIN: {
        REQUEST: 'TEAM_LOGIN_REQUEST',
        SUCCESS: 'TEAM_LOGIN_SUCCESS',
        FAILURE: 'TEAM_LOGIN_FAILURE'
    },
    LOGOUT: 'TEAM_LOGOUT',
    FIND_PLAYERS: {
        REQUEST: 'TEAM_FIND_PLAYERS_REQUEST',
        SUCCESS: 'TEAM_FIND_PLAYERS_SUCCESS',
        FAILURE: 'TEAM_FIND_PLAYERS_FAILURE'
    },
    REGISTER_PLAYER: {
        REQUEST: 'TEAM_REGISTER_PLAYER_REQUEST',
        SUCCESS: 'TEAM_REGISTER_PLAYER_SUCCESS',
        FAILURE: 'TEAM_REGISTER_PLAYER_FAILURE'
    }
}